; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

; Packed Averaging Addition and Subtraction

declare <4 x i8> @llvm.riscv.paadd.v4i8(<4 x i8>, <4 x i8>)

define <4 x i8> @paadd_i8x4(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: paadd_i8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    paadd.b a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <4 x i8> @llvm.riscv.paadd.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %tmp
}

declare <2 x i16> @llvm.riscv.paadd.v2i16(<2 x i16>, <2 x i16>)

define <2 x i16> @paadd_i16x2(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: paadd_i16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    paadd.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <2 x i16> @llvm.riscv.paadd.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %tmp
}

declare <4 x i8> @llvm.riscv.paaddu.v4i8(<4 x i8>, <4 x i8>)

define <4 x i8> @paaddu_u8x4(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: paaddu_u8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    paaddu.b a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <4 x i8> @llvm.riscv.paaddu.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %tmp
}

declare <2 x i16> @llvm.riscv.paaddu.v2i16(<2 x i16>, <2 x i16>)

define <2 x i16> @paaddu_u16x2(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: paaddu_u16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    paaddu.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <2 x i16> @llvm.riscv.paaddu.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %tmp
}

declare <4 x i8> @llvm.riscv.pasub.v4i8(<4 x i8>, <4 x i8>)

define <4 x i8> @pasub_i8x4(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pasub_i8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pasub.b a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <4 x i8> @llvm.riscv.pasub.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %tmp
}

declare <2 x i16> @llvm.riscv.pasub.v2i16(<2 x i16>, <2 x i16>)

define <2 x i16> @pasub_i16x2(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pasub_i16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pasub.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <2 x i16> @llvm.riscv.pasub.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %tmp
}

declare <4 x i8> @llvm.riscv.pasubu.v4i8(<4 x i8>, <4 x i8>)

define <4 x i8> @pasubu_u8x4(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pasubu_u8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pasubu.b a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <4 x i8> @llvm.riscv.pasubu.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %tmp
}

declare <2 x i16> @llvm.riscv.pasubu.v2i16(<2 x i16>, <2 x i16>)

define <2 x i16> @pasubu_u16x2(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pasubu_u16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pasubu.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <2 x i16> @llvm.riscv.pasubu.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %tmp
}

; Packed Absolute Value and Absolute Difference

declare <4 x i8> @llvm.riscv.pabs.v4i8(<4 x i8>)

define <4 x i8> @pabs_i8x4(<4 x i8> %a) {
; RV32P-LABEL: pabs_i8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pabd.b a0, a0, zero
; RV32P-NEXT:    ret
entry:
  %tmp = call <4 x i8> @llvm.riscv.pabs.v4i8(<4 x i8> %a)
  ret <4 x i8> %tmp
}

declare <2 x i16> @llvm.riscv.pabs.v2i16(<2 x i16>)

define <2 x i16> @pabs_i16x2(<2 x i16> %a) {
; RV32P-LABEL: pabs_i16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pabd.h a0, a0, zero
; RV32P-NEXT:    ret
entry:
  %tmp = call <2 x i16> @llvm.riscv.pabs.v2i16(<2 x i16> %a)
  ret <2 x i16> %tmp
}

declare <4 x i8> @llvm.riscv.pabd.v4i8(<4 x i8>, <4 x i8>)

define <4 x i8> @pabd_i8x4(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pabd_i8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pabd.b a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <4 x i8> @llvm.riscv.pabd.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %tmp
}

declare <2 x i16> @llvm.riscv.pabd.v2i16(<2 x i16>, <2 x i16>)

define <2 x i16> @pabd_i16x2(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pabd_i16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pabd.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <2 x i16> @llvm.riscv.pabd.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %tmp
}

declare <4 x i8> @llvm.riscv.pabdu.v4i8(<4 x i8>, <4 x i8>)

define <4 x i8> @pabdu_u8x4(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pabdu_u8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pabdu.b a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <4 x i8> @llvm.riscv.pabdu.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %tmp
}

declare <2 x i16> @llvm.riscv.pabdu.v2i16(<2 x i16>, <2 x i16>)

define <2 x i16> @pabdu_u16x2(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pabdu_u16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pabdu.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <2 x i16> @llvm.riscv.pabdu.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %tmp
}

; Packed Merge

define <4 x i8> @pmerge_u8x4(<4 x i8> %a, <4 x i8> %b, <4 x i8> %m) {
; RV32P-LABEL: pmerge_u8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    mvm a0, a1, a2
; RV32P-NEXT:    ret
entry:
  %nm = xor <4 x i8> %m, <i8 -1, i8 -1, i8 -1, i8 -1>
  %x = and <4 x i8> %a, %nm
  %y = and <4 x i8> %b, %m
  %r = or <4 x i8> %x, %y
  ret <4 x i8> %r
}

define <4 x i8> @pmerge_i8x4(<4 x i8> %a, <4 x i8> %b, <4 x i8> %m) {
; RV32P-LABEL: pmerge_i8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    mvm a0, a1, a2
; RV32P-NEXT:    ret
entry:
  %nm = xor <4 x i8> %m, <i8 -1, i8 -1, i8 -1, i8 -1>
  %x = and <4 x i8> %a, %nm
  %y = and <4 x i8> %b, %m
  %r = or <4 x i8> %x, %y
  ret <4 x i8> %r
}

define <2 x i16> @pmerge_u16x2(<2 x i16> %a, <2 x i16> %b, <2 x i16> %m) {
; RV32P-LABEL: pmerge_u16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    mvm a0, a1, a2
; RV32P-NEXT:    ret
entry:
  %nm = xor <2 x i16> %m, <i16 -1, i16 -1>
  %x = and <2 x i16> %a, %nm
  %y = and <2 x i16> %b, %m
  %r = or <2 x i16> %x, %y
  ret <2 x i16> %r
}

define <2 x i16> @pmerge_i16x2(<2 x i16> %a, <2 x i16> %b, <2 x i16> %m) {
; RV32P-LABEL: pmerge_i16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    mvm a0, a1, a2
; RV32P-NEXT:    ret
entry:
  %nm = xor <2 x i16> %m, <i16 -1, i16 -1>
  %x = and <2 x i16> %a, %nm
  %y = and <2 x i16> %b, %m
  %r = or <2 x i16> %x, %y
  ret <2 x i16> %r
}

define <8 x i8> @pmerge_u8x8(<8 x i8> %a, <8 x i8> %b, <8 x i8> %m) {
; RV32P-LABEL: pmerge_u8x8:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    mvm a0, a2, a4
; RV32P-NEXT:    mvm a1, a3, a5
; RV32P-NEXT:    ret
entry:
  %nm = xor <8 x i8> %m, <i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1>
  %x = and <8 x i8> %a, %nm
  %y = and <8 x i8> %b, %m
  %r = or <8 x i8> %x, %y
  ret <8 x i8> %r
}

define <8 x i8> @pmerge_i8x8(<8 x i8> %a, <8 x i8> %b, <8 x i8> %m) {
; RV32P-LABEL: pmerge_i8x8:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    mvm a0, a2, a4
; RV32P-NEXT:    mvm a1, a3, a5
; RV32P-NEXT:    ret
entry:
  %nm = xor <8 x i8> %m, <i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1>
  %x = and <8 x i8> %a, %nm
  %y = and <8 x i8> %b, %m
  %r = or <8 x i8> %x, %y
  ret <8 x i8> %r
}

define <4 x i16> @pmerge_u16x4(<4 x i16> %a, <4 x i16> %b, <4 x i16> %m) {
; RV32P-LABEL: pmerge_u16x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    mvm a0, a2, a4
; RV32P-NEXT:    mvm a1, a3, a5
; RV32P-NEXT:    ret
entry:
  %nm = xor <4 x i16> %m, <i16 -1, i16 -1, i16 -1, i16 -1>
  %x = and <4 x i16> %a, %nm
  %y = and <4 x i16> %b, %m
  %r = or <4 x i16> %x, %y
  ret <4 x i16> %r
}

define <4 x i16> @pmerge_i16x4(<4 x i16> %a, <4 x i16> %b, <4 x i16> %m) {
; RV32P-LABEL: pmerge_i16x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    mvm a0, a2, a4
; RV32P-NEXT:    mvm a1, a3, a5
; RV32P-NEXT:    ret
entry:
  %nm = xor <4 x i16> %m, <i16 -1, i16 -1, i16 -1, i16 -1>
  %x = and <4 x i16> %a, %nm
  %y = and <4 x i16> %b, %m
  %r = or <4 x i16> %x, %y
  ret <4 x i16> %r
}

define <2 x i32> @pmerge_u32x2(<2 x i32> %a, <2 x i32> %b, <2 x i32> %m) {
; RV32P-LABEL: pmerge_u32x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    mvm a0, a2, a4
; RV32P-NEXT:    mvm a1, a3, a5
; RV32P-NEXT:    ret
entry:
  %nm = xor <2 x i32> %m, <i32 -1, i32 -1>
  %x = and <2 x i32> %a, %nm
  %y = and <2 x i32> %b, %m
  %r = or <2 x i32> %x, %y
  ret <2 x i32> %r
}

define <2 x i32> @pmerge_i32x2(<2 x i32> %a, <2 x i32> %b, <2 x i32> %m) {
; RV32P-LABEL: pmerge_i32x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    mvm a0, a2, a4
; RV32P-NEXT:    mvm a1, a3, a5
; RV32P-NEXT:    ret
entry:
  %nm = xor <2 x i32> %m, <i32 -1, i32 -1>
  %x = and <2 x i32> %a, %nm
  %y = and <2 x i32> %b, %m
  %r = or <2 x i32> %x, %y
  ret <2 x i32> %r
}

; Packed Reduction Sum

declare i32 @llvm.riscv.predsum.i32.v4i8(<4 x i8>, i32)
declare i32 @llvm.riscv.predsumu.i32.v4i8(<4 x i8>, i32)
declare i32 @llvm.riscv.predsum.i32.v2i16(<2 x i16>, i32)
declare i32 @llvm.riscv.predsumu.i32.v2i16(<2 x i16>, i32)

define i32 @predsum_i8x4_i32(<4 x i8> %a, i32 %b) {
; RV32P-LABEL: predsum_i8x4_i32:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    predsum.bs a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %sum = call i32 @llvm.riscv.predsum.i32.v4i8(<4 x i8> %a, i32 %b)
  ret i32 %sum
}

define i32 @predsumu_u8x4_u32(<4 x i8> %a, i32 %b) {
; RV32P-LABEL: predsumu_u8x4_u32:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    predsumu.bs a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %sum = call i32 @llvm.riscv.predsumu.i32.v4i8(<4 x i8> %a, i32 %b)
  ret i32 %sum
}

define i32 @predsum_i16x2_i32(<2 x i16> %a, i32 %b) {
; RV32P-LABEL: predsum_i16x2_i32:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    predsum.hs a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %sum = call i32 @llvm.riscv.predsum.i32.v2i16(<2 x i16> %a, i32 %b)
  ret i32 %sum
}

define i32 @predsumu_u16x2_u32(<2 x i16> %a, i32 %b) {
; RV32P-LABEL: predsumu_u16x2_u32:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    predsumu.hs a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %sum = call i32 @llvm.riscv.predsumu.i32.v2i16(<2 x i16> %a, i32 %b)
  ret i32 %sum
}

; Packed Absolute Difference Sum

declare i32 @llvm.riscv.pabdsumu.i32.v4i8(<4 x i8>, <4 x i8>)

define i32 @pabdsumu_u8x4_u32(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pabdsumu_u8x4_u32:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pabdsumu.b a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %sum = call i32 @llvm.riscv.pabdsumu.i32.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret i32 %sum
}

define i32 @pabdsumau_u8x4_u32(i32 %rd, <4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pabdsumau_u8x4_u32:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pabdsumau.b a0, a1, a2
; RV32P-NEXT:    ret
entry:
  %sum = call i32 @llvm.riscv.pabdsumau.i32.v4i8(i32 %rd, <4 x i8> %a, <4 x i8> %b)
  ret i32 %sum
}

define i32 @pabdsumu_u8x8_u32(i64 %a, i64 %b) {
; RV32P-LABEL: pabdsumu_u8x8_u32:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pabdsumu.b a0, a0, a2
; RV32P-NEXT:    pabdsumau.b a0, a1, a3
; RV32P-NEXT:    ret
entry:
  %a.lo = trunc i64 %a to i32
  %va.lo = bitcast i32 %a.lo to <4 x i8>
  %a.hi.sh = lshr i64 %a, 32
  %a.hi = trunc i64 %a.hi.sh to i32
  %va.hi = bitcast i32 %a.hi to <4 x i8>
  %b.lo = trunc i64 %b to i32
  %vb.lo = bitcast i32 %b.lo to <4 x i8>
  %b.hi.sh = lshr i64 %b, 32
  %b.hi = trunc i64 %b.hi.sh to i32
  %vb.hi = bitcast i32 %b.hi to <4 x i8>
  %sum.lo = call i32 @llvm.riscv.pabdsumu.i32.v4i8(<4 x i8> %va.lo, <4 x i8> %vb.lo)
  %sum = call i32 @llvm.riscv.pabdsumau.i32.v4i8(i32 %sum.lo, <4 x i8> %va.hi, <4 x i8> %vb.hi)
  ret i32 %sum
}

define i64 @pabdsumu_u8x8_u64(i64 %a, i64 %b) {
; RV32P-LABEL: pabdsumu_u8x8_u64:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pabdsumu.b a0, a0, a2
; RV32P-NEXT:    pabdsumu.b a1, a1, a3
; RV32P-NEXT:    waddu a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %a.lo = trunc i64 %a to i32
  %va.lo = bitcast i32 %a.lo to <4 x i8>
  %a.hi.sh = lshr i64 %a, 32
  %a.hi = trunc i64 %a.hi.sh to i32
  %va.hi = bitcast i32 %a.hi to <4 x i8>
  %b.lo = trunc i64 %b to i32
  %vb.lo = bitcast i32 %b.lo to <4 x i8>
  %b.hi.sh = lshr i64 %b, 32
  %b.hi = trunc i64 %b.hi.sh to i32
  %vb.hi = bitcast i32 %b.hi to <4 x i8>
  %sum.lo = call i32 @llvm.riscv.pabdsumu.i32.v4i8(<4 x i8> %va.lo, <4 x i8> %vb.lo)
  %sum.hi = call i32 @llvm.riscv.pabdsumu.i32.v4i8(<4 x i8> %va.hi, <4 x i8> %vb.hi)
  %sum.lo.z = zext i32 %sum.lo to i64
  %sum.hi.z = zext i32 %sum.hi to i64
  %sum = add i64 %sum.lo.z, %sum.hi.z
  ret i64 %sum
}

define i32 @pabdsumau_u8x8_u32(i32 %rd, i64 %a, i64 %b) {
; RV32P-LABEL: pabdsumau_u8x8_u32:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pabdsumau.b a0, a1, a3
; RV32P-NEXT:    pabdsumau.b a0, a2, a4
; RV32P-NEXT:    ret
entry:
  %a.lo = trunc i64 %a to i32
  %va.lo = bitcast i32 %a.lo to <4 x i8>
  %a.hi.sh = lshr i64 %a, 32
  %a.hi = trunc i64 %a.hi.sh to i32
  %va.hi = bitcast i32 %a.hi to <4 x i8>
  %b.lo = trunc i64 %b to i32
  %vb.lo = bitcast i32 %b.lo to <4 x i8>
  %b.hi.sh = lshr i64 %b, 32
  %b.hi = trunc i64 %b.hi.sh to i32
  %vb.hi = bitcast i32 %b.hi to <4 x i8>
  %sum.lo = call i32 @llvm.riscv.pabdsumau.i32.v4i8(i32 %rd, <4 x i8> %va.lo, <4 x i8> %vb.lo)
  %sum = call i32 @llvm.riscv.pabdsumau.i32.v4i8(i32 %sum.lo, <4 x i8> %va.hi, <4 x i8> %vb.hi)
  ret i32 %sum
}

define i64 @pabdsumau_u8x8_u64(i64 %rd, i64 %a, i64 %b) {
; RV32P-LABEL: pabdsumau_u8x8_u64:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pabdsumu.b a2, a2, a4
; RV32P-NEXT:    pabdsumu.b a3, a3, a5
; RV32P-NEXT:    waddau a0, a2, a3
; RV32P-NEXT:    ret
entry:
  %a.lo = trunc i64 %a to i32
  %va.lo = bitcast i32 %a.lo to <4 x i8>
  %a.hi.sh = lshr i64 %a, 32
  %a.hi = trunc i64 %a.hi.sh to i32
  %va.hi = bitcast i32 %a.hi to <4 x i8>
  %b.lo = trunc i64 %b to i32
  %vb.lo = bitcast i32 %b.lo to <4 x i8>
  %b.hi.sh = lshr i64 %b, 32
  %b.hi = trunc i64 %b.hi.sh to i32
  %vb.hi = bitcast i32 %b.hi to <4 x i8>
  %sum.lo = call i32 @llvm.riscv.pabdsumu.i32.v4i8(<4 x i8> %va.lo, <4 x i8> %vb.lo)
  %sum.hi = call i32 @llvm.riscv.pabdsumu.i32.v4i8(<4 x i8> %va.hi, <4 x i8> %vb.hi)
  %sum.lo.z = zext i32 %sum.lo to i64
  %acc = add i64 %rd, %sum.lo.z
  %sum.hi.z = zext i32 %sum.hi to i64
  %sum = add i64 %acc, %sum.hi.z
  ret i64 %sum
}

; Packed Saturating Absolute Value

declare <4 x i8> @llvm.riscv.psabs.v4i8(<4 x i8>)

define <4 x i8> @psabs_i8x4(<4 x i8> %a) {
; RV32P-LABEL: psabs_i8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    psabs.b a0, a0
; RV32P-NEXT:    ret
entry:
  %tmp = call <4 x i8> @llvm.riscv.psabs.v4i8(<4 x i8> %a)
  ret <4 x i8> %tmp
}

declare <2 x i16> @llvm.riscv.psabs.v2i16(<2 x i16>)

define <2 x i16> @psabs_i16x2(<2 x i16> %a) {
; RV32P-LABEL: psabs_i16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    psabs.h a0, a0
; RV32P-NEXT:    ret
entry:
  %tmp = call <2 x i16> @llvm.riscv.psabs.v2i16(<2 x i16> %a)
  ret <2 x i16> %tmp
}

define i64 @psabs_i8x8(i64 %a) {
; RV32P-LABEL: psabs_i8x8:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    psabs.b a0, a0
; RV32P-NEXT:    psabs.b a1, a1
; RV32P-NEXT:    ret
entry:
  %0 = trunc i64 %a to i32
  %1 = bitcast i32 %0 to <4 x i8>
  %2 = lshr i64 %a, 32
  %3 = trunc nuw i64 %2 to i32
  %4 = bitcast i32 %3 to <4 x i8>
  %5 = call <4 x i8> @llvm.riscv.psabs.v4i8(<4 x i8> %1)
  %6 = call <4 x i8> @llvm.riscv.psabs.v4i8(<4 x i8> %4)
  %7 = bitcast <4 x i8> %5 to i32
  %8 = zext i32 %7 to i64
  %9 = bitcast <4 x i8> %6 to i32
  %10 = zext i32 %9 to i64
  %11 = shl nuw i64 %10, 32
  %12 = or disjoint i64 %11, %8
  ret i64 %12
}

define i64 @psabs_i16x4(i64 %a) {
; RV32P-LABEL: psabs_i16x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    psabs.h a0, a0
; RV32P-NEXT:    psabs.h a1, a1
; RV32P-NEXT:    ret
entry:
  %0 = trunc i64 %a to i32
  %1 = bitcast i32 %0 to <2 x i16>
  %2 = lshr i64 %a, 32
  %3 = trunc nuw i64 %2 to i32
  %4 = bitcast i32 %3 to <2 x i16>
  %5 = call <2 x i16> @llvm.riscv.psabs.v2i16(<2 x i16> %1)
  %6 = call <2 x i16> @llvm.riscv.psabs.v2i16(<2 x i16> %4)
  %7 = bitcast <2 x i16> %5 to i32
  %8 = zext i32 %7 to i64
  %9 = bitcast <2 x i16> %6 to i32
  %10 = zext i32 %9 to i64
  %11 = shl nuw i64 %10, 32
  %12 = or disjoint i64 %11, %8
  ret i64 %12
}
