; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare <4 x i8> @llvm.riscv.paadd.v4i8(<4 x i8>, <4 x i8>)

define <4 x i8> @paadd_i8x4(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: paadd_i8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    paadd.b a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <4 x i8> @llvm.riscv.paadd.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %tmp
}

declare <2 x i16> @llvm.riscv.paadd.v2i16(<2 x i16>, <2 x i16>)

define <2 x i16> @paadd_i16x2(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: paadd_i16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    paadd.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <2 x i16> @llvm.riscv.paadd.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %tmp
}

declare <4 x i8> @llvm.riscv.paaddu.v4i8(<4 x i8>, <4 x i8>)
define <4 x i8> @paaddu_i8x4(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: paaddu_i8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    paaddu.b a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <4 x i8> @llvm.riscv.paaddu.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %tmp
}

declare <2 x i16> @llvm.riscv.paaddu.v2i16(<2 x i16>, <2 x i16>)
define <2 x i16> @paaddu_i16x2(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: paaddu_i16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    paaddu.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <2 x i16> @llvm.riscv.paaddu.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %tmp
}

declare <4 x i8> @llvm.riscv.pasub.v4i8(<4 x i8>, <4 x i8>)

define <4 x i8> @pasub_i8x4(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pasub_i8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pasub.b a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <4 x i8> @llvm.riscv.pasub.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %tmp
}

declare <2 x i16> @llvm.riscv.pasub.v2i16(<2 x i16>, <2 x i16>)

define <2 x i16> @pasub_i16x2(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pasub_i16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pasub.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <2 x i16> @llvm.riscv.pasub.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %tmp
}

declare <4 x i8> @llvm.riscv.pasubu.v4i8(<4 x i8>, <4 x i8>)
define <4 x i8> @pasubu_i8x4(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pasubu_i8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pasubu.b a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <4 x i8> @llvm.riscv.pasubu.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %tmp
}

declare <2 x i16> @llvm.riscv.pasubu.v2i16(<2 x i16>, <2 x i16>)
define <2 x i16> @pasubu_i16x2(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pasubu_i16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pasubu.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <2 x i16> @llvm.riscv.pasubu.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %tmp
}
