; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

; Packed Averaging Addition and Subtraction

declare <4 x i8> @llvm.riscv.paadd.v4i8(<4 x i8>, <4 x i8>)

define <4 x i8> @paadd_i8x4(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: paadd_i8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    paadd.b a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <4 x i8> @llvm.riscv.paadd.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %tmp
}

declare <2 x i16> @llvm.riscv.paadd.v2i16(<2 x i16>, <2 x i16>)

define <2 x i16> @paadd_i16x2(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: paadd_i16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    paadd.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <2 x i16> @llvm.riscv.paadd.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %tmp
}

declare <4 x i8> @llvm.riscv.paaddu.v4i8(<4 x i8>, <4 x i8>)

define <4 x i8> @paaddu_u8x4(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: paaddu_u8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    paaddu.b a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <4 x i8> @llvm.riscv.paaddu.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %tmp
}

declare <2 x i16> @llvm.riscv.paaddu.v2i16(<2 x i16>, <2 x i16>)

define <2 x i16> @paaddu_u16x2(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: paaddu_u16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    paaddu.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <2 x i16> @llvm.riscv.paaddu.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %tmp
}

declare <4 x i8> @llvm.riscv.pasub.v4i8(<4 x i8>, <4 x i8>)

define <4 x i8> @pasub_i8x4(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pasub_i8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pasub.b a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <4 x i8> @llvm.riscv.pasub.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %tmp
}

declare <2 x i16> @llvm.riscv.pasub.v2i16(<2 x i16>, <2 x i16>)

define <2 x i16> @pasub_i16x2(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pasub_i16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pasub.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <2 x i16> @llvm.riscv.pasub.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %tmp
}

declare <4 x i8> @llvm.riscv.pasubu.v4i8(<4 x i8>, <4 x i8>)

define <4 x i8> @pasubu_u8x4(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pasubu_u8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pasubu.b a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <4 x i8> @llvm.riscv.pasubu.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %tmp
}

declare <2 x i16> @llvm.riscv.pasubu.v2i16(<2 x i16>, <2 x i16>)

define <2 x i16> @pasubu_u16x2(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pasubu_u16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pasubu.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <2 x i16> @llvm.riscv.pasubu.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %tmp
}

; Packed Absolute Value and Absolute Difference

declare <4 x i8> @llvm.riscv.pabs.v4i8(<4 x i8>)

define <4 x i8> @pabs_i8x4(<4 x i8> %a) {
; RV32P-LABEL: pabs_i8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pabd.b a0, a0, zero
; RV32P-NEXT:    ret
entry:
  %tmp = call <4 x i8> @llvm.riscv.pabs.v4i8(<4 x i8> %a)
  ret <4 x i8> %tmp
}

declare <2 x i16> @llvm.riscv.pabs.v2i16(<2 x i16>)

define <2 x i16> @pabs_i16x2(<2 x i16> %a) {
; RV32P-LABEL: pabs_i16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pabd.h a0, a0, zero
; RV32P-NEXT:    ret
entry:
  %tmp = call <2 x i16> @llvm.riscv.pabs.v2i16(<2 x i16> %a)
  ret <2 x i16> %tmp
}

declare <4 x i8> @llvm.riscv.pabd.v4i8(<4 x i8>, <4 x i8>)

define <4 x i8> @pabd_i8x4(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pabd_i8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pabd.b a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <4 x i8> @llvm.riscv.pabd.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %tmp
}

declare <2 x i16> @llvm.riscv.pabd.v2i16(<2 x i16>, <2 x i16>)

define <2 x i16> @pabd_i16x2(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pabd_i16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pabd.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <2 x i16> @llvm.riscv.pabd.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %tmp
}

declare <4 x i8> @llvm.riscv.pabdu.v4i8(<4 x i8>, <4 x i8>)

define <4 x i8> @pabdu_u8x4(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pabdu_u8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pabdu.b a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <4 x i8> @llvm.riscv.pabdu.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %tmp
}

declare <2 x i16> @llvm.riscv.pabdu.v2i16(<2 x i16>, <2 x i16>)

define <2 x i16> @pabdu_u16x2(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pabdu_u16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pabdu.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %tmp = call <2 x i16> @llvm.riscv.pabdu.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %tmp
}

; Packed Merge

define <4 x i8> @pmerge_u8x4(<4 x i8> %a, <4 x i8> %b, <4 x i8> %m) {
; RV32P-LABEL: pmerge_u8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    mvm a0, a1, a2
; RV32P-NEXT:    ret
entry:
  %nm = xor <4 x i8> %m, <i8 -1, i8 -1, i8 -1, i8 -1>
  %x = and <4 x i8> %a, %nm
  %y = and <4 x i8> %b, %m
  %r = or <4 x i8> %x, %y
  ret <4 x i8> %r
}

define <4 x i8> @pmerge_i8x4(<4 x i8> %a, <4 x i8> %b, <4 x i8> %m) {
; RV32P-LABEL: pmerge_i8x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    mvm a0, a1, a2
; RV32P-NEXT:    ret
entry:
  %nm = xor <4 x i8> %m, <i8 -1, i8 -1, i8 -1, i8 -1>
  %x = and <4 x i8> %a, %nm
  %y = and <4 x i8> %b, %m
  %r = or <4 x i8> %x, %y
  ret <4 x i8> %r
}

define <2 x i16> @pmerge_u16x2(<2 x i16> %a, <2 x i16> %b, <2 x i16> %m) {
; RV32P-LABEL: pmerge_u16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    mvm a0, a1, a2
; RV32P-NEXT:    ret
entry:
  %nm = xor <2 x i16> %m, <i16 -1, i16 -1>
  %x = and <2 x i16> %a, %nm
  %y = and <2 x i16> %b, %m
  %r = or <2 x i16> %x, %y
  ret <2 x i16> %r
}

define <2 x i16> @pmerge_i16x2(<2 x i16> %a, <2 x i16> %b, <2 x i16> %m) {
; RV32P-LABEL: pmerge_i16x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    mvm a0, a1, a2
; RV32P-NEXT:    ret
entry:
  %nm = xor <2 x i16> %m, <i16 -1, i16 -1>
  %x = and <2 x i16> %a, %nm
  %y = and <2 x i16> %b, %m
  %r = or <2 x i16> %x, %y
  ret <2 x i16> %r
}

define <8 x i8> @pmerge_u8x8(<8 x i8> %a, <8 x i8> %b, <8 x i8> %m) {
; RV32P-LABEL: pmerge_u8x8:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    mvm a0, a2, a4
; RV32P-NEXT:    mvm a1, a3, a5
; RV32P-NEXT:    ret
entry:
  %nm = xor <8 x i8> %m, <i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1>
  %x = and <8 x i8> %a, %nm
  %y = and <8 x i8> %b, %m
  %r = or <8 x i8> %x, %y
  ret <8 x i8> %r
}

define <8 x i8> @pmerge_i8x8(<8 x i8> %a, <8 x i8> %b, <8 x i8> %m) {
; RV32P-LABEL: pmerge_i8x8:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    mvm a0, a2, a4
; RV32P-NEXT:    mvm a1, a3, a5
; RV32P-NEXT:    ret
entry:
  %nm = xor <8 x i8> %m, <i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1>
  %x = and <8 x i8> %a, %nm
  %y = and <8 x i8> %b, %m
  %r = or <8 x i8> %x, %y
  ret <8 x i8> %r
}

define <4 x i16> @pmerge_u16x4(<4 x i16> %a, <4 x i16> %b, <4 x i16> %m) {
; RV32P-LABEL: pmerge_u16x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    mvm a0, a2, a4
; RV32P-NEXT:    mvm a1, a3, a5
; RV32P-NEXT:    ret
entry:
  %nm = xor <4 x i16> %m, <i16 -1, i16 -1, i16 -1, i16 -1>
  %x = and <4 x i16> %a, %nm
  %y = and <4 x i16> %b, %m
  %r = or <4 x i16> %x, %y
  ret <4 x i16> %r
}

define <4 x i16> @pmerge_i16x4(<4 x i16> %a, <4 x i16> %b, <4 x i16> %m) {
; RV32P-LABEL: pmerge_i16x4:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    mvm a0, a2, a4
; RV32P-NEXT:    mvm a1, a3, a5
; RV32P-NEXT:    ret
entry:
  %nm = xor <4 x i16> %m, <i16 -1, i16 -1, i16 -1, i16 -1>
  %x = and <4 x i16> %a, %nm
  %y = and <4 x i16> %b, %m
  %r = or <4 x i16> %x, %y
  ret <4 x i16> %r
}

define <2 x i32> @pmerge_u32x2(<2 x i32> %a, <2 x i32> %b, <2 x i32> %m) {
; RV32P-LABEL: pmerge_u32x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    mvm a0, a2, a4
; RV32P-NEXT:    mvm a1, a3, a5
; RV32P-NEXT:    ret
entry:
  %nm = xor <2 x i32> %m, <i32 -1, i32 -1>
  %x = and <2 x i32> %a, %nm
  %y = and <2 x i32> %b, %m
  %r = or <2 x i32> %x, %y
  ret <2 x i32> %r
}

define <2 x i32> @pmerge_i32x2(<2 x i32> %a, <2 x i32> %b, <2 x i32> %m) {
; RV32P-LABEL: pmerge_i32x2:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    mvm a0, a2, a4
; RV32P-NEXT:    mvm a1, a3, a5
; RV32P-NEXT:    ret
entry:
  %nm = xor <2 x i32> %m, <i32 -1, i32 -1>
  %x = and <2 x i32> %a, %nm
  %y = and <2 x i32> %b, %m
  %r = or <2 x i32> %x, %y
  ret <2 x i32> %r
}
