; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64P

; Packed Averaging Addition and Subtraction

declare <8 x i8>  @llvm.riscv.paadd.v8i8(<8 x i8>, <8 x i8>)

define <8 x i8> @paadd_i8x8(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: paadd_i8x8:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    paadd.b a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <8 x i8> @llvm.riscv.paadd.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <8 x i8> %tmp
}

declare <4 x i16> @llvm.riscv.paadd.v4i16(<4 x i16>, <4 x i16>)

define <4 x i16> @paadd_i16x4(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: paadd_i16x4:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    paadd.h a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <4 x i16> @llvm.riscv.paadd.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %tmp
}

declare <2 x i32> @llvm.riscv.paadd.v2i32(<2 x i32>, <2 x i32>)

define <2 x i32> @paadd_i32x2(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: paadd_i32x2:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    paadd.w a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <2 x i32> @llvm.riscv.paadd.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %tmp
}

declare <8 x i8> @llvm.riscv.paaddu.v8i8(<8 x i8>, <8 x i8>)

define <8 x i8> @paaddu_u8x8(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: paaddu_u8x8:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    paaddu.b a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <8 x i8> @llvm.riscv.paaddu.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <8 x i8> %tmp
}

declare <4 x i16> @llvm.riscv.paaddu.v4i16(<4 x i16>, <4 x i16>)

define <4 x i16> @paaddu_u16x4(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: paaddu_u16x4:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    paaddu.h a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <4 x i16> @llvm.riscv.paaddu.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %tmp
}

declare <2 x i32> @llvm.riscv.paaddu.v2i32(<2 x i32>, <2 x i32>)

define <2 x i32> @paaddu_u32x2(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: paaddu_u32x2:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    paaddu.w a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <2 x i32> @llvm.riscv.paaddu.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %tmp
}

declare <8 x i8>  @llvm.riscv.pasub.v8i8(<8 x i8>, <8 x i8>)

define <8 x i8> @pasub_i8x8(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: pasub_i8x8:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pasub.b a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <8 x i8> @llvm.riscv.pasub.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <8 x i8> %tmp
}

declare <4 x i16> @llvm.riscv.pasub.v4i16(<4 x i16>, <4 x i16>)

define <4 x i16> @pasub_i16x4(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pasub_i16x4:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pasub.h a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <4 x i16> @llvm.riscv.pasub.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %tmp
}

declare <2 x i32> @llvm.riscv.pasub.v2i32(<2 x i32>, <2 x i32>)

define <2 x i32> @pasub_i32x2(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pasub_i32x2:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pasub.w a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <2 x i32> @llvm.riscv.pasub.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %tmp
}

declare <8 x i8>  @llvm.riscv.pasubu.v8i8(<8 x i8>, <8 x i8>)

define <8 x i8> @pasubu_u8x8(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: pasubu_u8x8:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pasubu.b a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <8 x i8> @llvm.riscv.pasubu.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <8 x i8> %tmp
}

declare <4 x i16> @llvm.riscv.pasubu.v4i16(<4 x i16>, <4 x i16>)

define <4 x i16> @pasubu_u16x4(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pasubu_u16x4:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pasubu.h a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <4 x i16> @llvm.riscv.pasubu.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %tmp
}

declare <2 x i32> @llvm.riscv.pasubu.v2i32(<2 x i32>, <2 x i32>)

define <2 x i32> @pasubu_u32x2(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pasubu_u32x2:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pasubu.w a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <2 x i32> @llvm.riscv.pasubu.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %tmp
}

; Packed Absolute Value and Absolute Difference

declare <8 x i8>  @llvm.riscv.pabs.v8i8(<8 x i8>)

define <8 x i8> @pabs_i8x8(<8 x i8> %a) {
; RV64P-LABEL: pabs_i8x8:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pabd.b a0, a0, zero
; RV64P-NEXT:    ret
entry:
  %tmp = call <8 x i8> @llvm.riscv.pabs.v8i8(<8 x i8> %a)
  ret <8 x i8> %tmp
}

declare <4 x i16> @llvm.riscv.pabs.v4i16(<4 x i16>)

define <4 x i16> @pabs_i16x4(<4 x i16> %a) {
; RV64P-LABEL: pabs_i16x4:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pabd.h a0, a0, zero
; RV64P-NEXT:    ret
entry:
  %tmp = call <4 x i16> @llvm.riscv.pabs.v4i16(<4 x i16> %a)
  ret <4 x i16> %tmp
}

declare <8 x i8>  @llvm.riscv.pabd.v8i8(<8 x i8>, <8 x i8>)

define <8 x i8> @pabd_i8x8(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: pabd_i8x8:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pabd.b a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <8 x i8> @llvm.riscv.pabd.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <8 x i8> %tmp
}

declare <4 x i16> @llvm.riscv.pabd.v4i16(<4 x i16>, <4 x i16>)

define <4 x i16> @pabd_i16x4(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pabd_i16x4:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pabd.h a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <4 x i16> @llvm.riscv.pabd.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %tmp
}

declare <8 x i8>  @llvm.riscv.pabdu.v8i8(<8 x i8>, <8 x i8>)

define <8 x i8> @pabdu_u8x8(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: pabdu_u8x8:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pabdu.b a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <8 x i8> @llvm.riscv.pabdu.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <8 x i8> %tmp
}

declare <4 x i16> @llvm.riscv.pabdu.v4i16(<4 x i16>, <4 x i16>)

define <4 x i16> @pabdu_u16x4(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pabdu_u16x4:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pabdu.h a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <4 x i16> @llvm.riscv.pabdu.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %tmp
}

; Packed merge

define <4 x i8> @pmerge_u8x4(<4 x i8> %a, <4 x i8> %b, <4 x i8> %m) {
; RV64P-LABEL: pmerge_u8x4:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    mvm a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %nm = xor <4 x i8> %m, <i8 -1, i8 -1, i8 -1, i8 -1>
  %x = and <4 x i8> %a, %nm
  %y = and <4 x i8> %b, %m
  %r = or <4 x i8> %x, %y
  ret <4 x i8> %r
}

define <4 x i8> @pmerge_i8x4(<4 x i8> %a, <4 x i8> %b, <4 x i8> %m) {
; RV64P-LABEL: pmerge_i8x4:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    mvm a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %nm = xor <4 x i8> %m, <i8 -1, i8 -1, i8 -1, i8 -1>
  %x = and <4 x i8> %a, %nm
  %y = and <4 x i8> %b, %m
  %r = or <4 x i8> %x, %y
  ret <4 x i8> %r
}

define <2 x i16> @pmerge_u16x2(<2 x i16> %a, <2 x i16> %b, <2 x i16> %m) {
; RV64P-LABEL: pmerge_u16x2:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    mvm a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %nm = xor <2 x i16> %m, <i16 -1, i16 -1>
  %x = and <2 x i16> %a, %nm
  %y = and <2 x i16> %b, %m
  %r = or <2 x i16> %x, %y
  ret <2 x i16> %r
}

define <2 x i16> @pmerge_i16x2(<2 x i16> %a, <2 x i16> %b, <2 x i16> %m) {
; RV64P-LABEL: pmerge_i16x2:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    mvm a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %nm = xor <2 x i16> %m, <i16 -1, i16 -1>
  %x = and <2 x i16> %a, %nm
  %y = and <2 x i16> %b, %m
  %r = or <2 x i16> %x, %y
  ret <2 x i16> %r
}

define <8 x i8> @pmerge_u8x8(<8 x i8> %a, <8 x i8> %b, <8 x i8> %m) {
; RV64P-LABEL: pmerge_u8x8:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    mvm a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %nm = xor <8 x i8> %m, <i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1>
  %x = and <8 x i8> %a, %nm
  %y = and <8 x i8> %b, %m
  %r = or <8 x i8> %x, %y
  ret <8 x i8> %r
}

define <8 x i8> @pmerge_i8x8(<8 x i8> %a, <8 x i8> %b, <8 x i8> %m) {
; RV64P-LABEL: pmerge_i8x8:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    mvm a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %nm = xor <8 x i8> %m, <i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1>
  %x = and <8 x i8> %a, %nm
  %y = and <8 x i8> %b, %m
  %r = or <8 x i8> %x, %y
  ret <8 x i8> %r
}

define <4 x i16> @pmerge_u16x4(<4 x i16> %a, <4 x i16> %b, <4 x i16> %m) {
; RV64P-LABEL: pmerge_u16x4:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    mvm a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %nm = xor <4 x i16> %m, <i16 -1, i16 -1, i16 -1, i16 -1>
  %x = and <4 x i16> %a, %nm
  %y = and <4 x i16> %b, %m
  %r = or <4 x i16> %x, %y
  ret <4 x i16> %r
}

define <4 x i16> @pmerge_i16x4(<4 x i16> %a, <4 x i16> %b, <4 x i16> %m) {
; RV64P-LABEL: pmerge_i16x4:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    mvm a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %nm = xor <4 x i16> %m, <i16 -1, i16 -1, i16 -1, i16 -1>
  %x = and <4 x i16> %a, %nm
  %y = and <4 x i16> %b, %m
  %r = or <4 x i16> %x, %y
  ret <4 x i16> %r
}

define <2 x i32> @pmerge_u32x2(<2 x i32> %a, <2 x i32> %b, <2 x i32> %m) {
; RV64P-LABEL: pmerge_u32x2:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    mvm a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %nm = xor <2 x i32> %m, <i32 -1, i32 -1>
  %x = and <2 x i32> %a, %nm
  %y = and <2 x i32> %b, %m
  %r = or <2 x i32> %x, %y
  ret <2 x i32> %r
}

define <2 x i32> @pmerge_i32x2(<2 x i32> %a, <2 x i32> %b, <2 x i32> %m) {
; RV64P-LABEL: pmerge_i32x2:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    mvm a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %nm = xor <2 x i32> %m, <i32 -1, i32 -1>
  %x = and <2 x i32> %a, %nm
  %y = and <2 x i32> %b, %m
  %r = or <2 x i32> %x, %y
  ret <2 x i32> %r
}

; Packed Reduction Sum

declare i64 @llvm.riscv.predsum.i64.v8i8(<8 x i8>, i64)
declare i64 @llvm.riscv.predsumu.i64.v8i8(<8 x i8>, i64)
declare i64 @llvm.riscv.predsum.i64.v4i16(<4 x i16>, i64)
declare i64 @llvm.riscv.predsumu.i64.v4i16(<4 x i16>, i64)
declare i64 @llvm.riscv.predsum.i64.v2i32(<2 x i32>, i64)
declare i64 @llvm.riscv.predsumu.i64.v2i32(<2 x i32>, i64)

define i64 @predsum_i8x8_i64(<8 x i8> %a, i64 %b) {
; RV64P-LABEL: predsum_i8x8_i64:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    predsum.bs a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %sum = call i64 @llvm.riscv.predsum.i64.v8i8(<8 x i8> %a, i64 %b)
  ret i64 %sum
}

define i64 @predsumu_u8x8_u64(<8 x i8> %a, i64 %b) {
; RV64P-LABEL: predsumu_u8x8_u64:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    predsumu.bs a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %sum = call i64 @llvm.riscv.predsumu.i64.v8i8(<8 x i8> %a, i64 %b)
  ret i64 %sum
}

define i64 @predsum_i16x4_i64(<4 x i16> %a, i64 %b) {
; RV64P-LABEL: predsum_i16x4_i64:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    predsum.hs a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %sum = call i64 @llvm.riscv.predsum.i64.v4i16(<4 x i16> %a, i64 %b)
  ret i64 %sum
}

define i64 @predsumu_u16x4_u64(<4 x i16> %a, i64 %b) {
; RV64P-LABEL: predsumu_u16x4_u64:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    predsumu.hs a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %sum = call i64 @llvm.riscv.predsumu.i64.v4i16(<4 x i16> %a, i64 %b)
  ret i64 %sum
}

define i64 @predsum_i32x2_i64(<2 x i32> %a, i64 %b) {
; RV64P-LABEL: predsum_i32x2_i64:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    predsum.ws a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %sum = call i64 @llvm.riscv.predsum.i64.v2i32(<2 x i32> %a, i64 %b)
  ret i64 %sum
}

define i64 @predsumu_u32x2_u64(<2 x i32> %a, i64 %b) {
; RV64P-LABEL: predsumu_u32x2_u64:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    predsumu.ws a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %sum = call i64 @llvm.riscv.predsumu.i64.v2i32(<2 x i32> %a, i64 %b)
  ret i64 %sum
}


; Packed Absolute Difference Sum

declare i64 @llvm.riscv.pabdsumu.i64.v8i8(<8 x i8>, <8 x i8>)
declare i64 @llvm.riscv.pabdsumau.i64.v8i8(i64, <8 x i8>, <8 x i8>)

define signext i32 @pabdsumu_u8x4_u32(i32 %a, i32 %b) {
; RV64P-LABEL: pabdsumu_u8x4_u32:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    zext.w a0, a0
; RV64P-NEXT:    zext.w a1, a1
; RV64P-NEXT:    pabdsumu.b a0, a0, a1
; RV64P-NEXT:    sext.w a0, a0
; RV64P-NEXT:    ret
entry:
  %a64 = zext i32 %a to i64
  %va = bitcast i64 %a64 to <8 x i8>
  %b64 = zext i32 %b to i64
  %vb = bitcast i64 %b64 to <8 x i8>
  %sum = call i64 @llvm.riscv.pabdsumu.i64.v8i8(<8 x i8> %va, <8 x i8> %vb)
  %r = trunc i64 %sum to i32
  ret i32 %r
}

define signext i32 @pabdsumau_u8x4_u32(i32 %rd, i32 %a, i32 %b) {
; RV64P-LABEL: pabdsumau_u8x4_u32:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    zext.w a1, a1
; RV64P-NEXT:    zext.w a2, a2
; RV64P-NEXT:    zext.w a0, a0
; RV64P-NEXT:    pabdsumau.b a0, a1, a2
; RV64P-NEXT:    sext.w a0, a0
; RV64P-NEXT:    ret
entry:
  %a64 = zext i32 %a to i64
  %va = bitcast i64 %a64 to <8 x i8>
  %b64 = zext i32 %b to i64
  %vb = bitcast i64 %b64 to <8 x i8>
  %rd64 = zext i32 %rd to i64
  %sum = call i64 @llvm.riscv.pabdsumau.i64.v8i8(i64 %rd64, <8 x i8> %va, <8 x i8> %vb)
  %r = trunc i64 %sum to i32
  ret i32 %r
}

define signext i32 @pabdsumu_u8x8_u32(i64 %a, i64 %b) {
; RV64P-LABEL: pabdsumu_u8x8_u32:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pabdsumu.b a0, a0, a1
; RV64P-NEXT:    sext.w a0, a0
; RV64P-NEXT:    ret
entry:
  %va = bitcast i64 %a to <8 x i8>
  %vb = bitcast i64 %b to <8 x i8>
  %sum = call i64 @llvm.riscv.pabdsumu.i64.v8i8(<8 x i8> %va, <8 x i8> %vb)
  %r = trunc i64 %sum to i32
  ret i32 %r
}

define i64 @pabdsumu_u8x8_u64(i64 %a, i64 %b) {
; RV64P-LABEL: pabdsumu_u8x8_u64:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pabdsumu.b a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %va = bitcast i64 %a to <8 x i8>
  %vb = bitcast i64 %b to <8 x i8>
  %sum = call i64 @llvm.riscv.pabdsumu.i64.v8i8(<8 x i8> %va, <8 x i8> %vb)
  ret i64 %sum
}

define signext i32 @pabdsumau_u8x8_u32(i32 %rd, i64 %a, i64 %b) {
; RV64P-LABEL: pabdsumau_u8x8_u32:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    zext.w a0, a0
; RV64P-NEXT:    pabdsumau.b a0, a1, a2
; RV64P-NEXT:    sext.w a0, a0
; RV64P-NEXT:    ret
entry:
  %va = bitcast i64 %a to <8 x i8>
  %vb = bitcast i64 %b to <8 x i8>
  %rd64 = zext i32 %rd to i64
  %sum = call i64 @llvm.riscv.pabdsumau.i64.v8i8(i64 %rd64, <8 x i8> %va, <8 x i8> %vb)
  %r = trunc i64 %sum to i32
  ret i32 %r
}

define i64 @pabdsumau_u8x8_u64(i64 %rd, i64 %a, i64 %b) {
; RV64P-LABEL: pabdsumau_u8x8_u64:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pabdsumau.b a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %va = bitcast i64 %a to <8 x i8>
  %vb = bitcast i64 %b to <8 x i8>
  %sum = call i64 @llvm.riscv.pabdsumau.i64.v8i8(i64 %rd, <8 x i8> %va, <8 x i8> %vb)
  ret i64 %sum
}

; Packed Saturating Absolute Value

declare <4 x i8> @llvm.riscv.psabs.v4i8(<4 x i8>)

define i32 @psabs_i8x4(i32 %a) {
; RV64P-LABEL: psabs_i8x4:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    zext.w a0, a0
; RV64P-NEXT:    psabs.b a0, a0
; RV64P-NEXT:    ret
entry:
  %0 = zext i32 %a to i64
  %1 = bitcast i64 %0 to <8 x i8>
  %2 = call <8 x i8> @llvm.riscv.psabs.v8i8(<8 x i8> %1)
  %3 = bitcast <8 x i8> %2 to <2 x i32>
  %4 = extractelement <2 x i32> %3, i64 0
  ret i32 %4
}

declare <2 x i16> @llvm.riscv.psabs.v2i16(<2 x i16>)

define i32 @psabs_i16x2(i32 %a) {
; RV64P-LABEL: psabs_i16x2:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    zext.w a0, a0
; RV64P-NEXT:    psabs.h a0, a0
; RV64P-NEXT:    ret
entry:
  %0 = zext i32 %a to i64
  %1 = bitcast i64 %0 to <4 x i16>
  %2 = call <4 x i16> @llvm.riscv.psabs.v4i16(<4 x i16> %1)
  %3 = bitcast <4 x i16> %2 to <2 x i32>
  %4 = extractelement <2 x i32> %3, i64 0
  ret i32 %4
}

declare <8 x i8>  @llvm.riscv.psabs.v8i8(<8 x i8>)

define <8 x i8> @psabs_i8x8(<8 x i8> %a) {
; RV64P-LABEL: psabs_i8x8:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    psabs.b a0, a0
; RV64P-NEXT:    ret
entry:
  %tmp = call <8 x i8> @llvm.riscv.psabs.v8i8(<8 x i8> %a)
  ret <8 x i8> %tmp
}

declare <4 x i16> @llvm.riscv.psabs.v4i16(<4 x i16>)

define <4 x i16> @psabs_i16x4(<4 x i16> %a) {
; RV64P-LABEL: psabs_i16x4:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    psabs.h a0, a0
; RV64P-NEXT:    ret
entry:
  %tmp = call <4 x i16> @llvm.riscv.psabs.v4i16(<4 x i16> %a)
  ret <4 x i16> %tmp
}
