; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64P

declare <8 x i8>  @llvm.riscv.paadd.v8i8(<8 x i8>, <8 x i8>)

define <8 x i8> @paadd_i8x8(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: paadd_i8x8:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    paadd.b a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <8 x i8> @llvm.riscv.paadd.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <8 x i8> %tmp
}

declare <4 x i16> @llvm.riscv.paadd.v4i16(<4 x i16>, <4 x i16>)

define <4 x i16> @paadd_i16x4(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: paadd_i16x4:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    paadd.h a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <4 x i16> @llvm.riscv.paadd.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %tmp
}

declare <2 x i32> @llvm.riscv.paadd.v2i32(<2 x i32>, <2 x i32>)

define <2 x i32> @paadd_i32x2(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: paadd_i32x2:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    paadd.w a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <2 x i32> @llvm.riscv.paadd.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %tmp
}

declare <8 x i8> @llvm.riscv.paaddu.v8i8(<8 x i8>, <8 x i8>)

define <8 x i8> @paaddu_i8x8(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: paaddu_i8x8:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    paaddu.b a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <8 x i8> @llvm.riscv.paaddu.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <8 x i8> %tmp
}

declare <4 x i16> @llvm.riscv.paaddu.v4i16(<4 x i16>, <4 x i16>)

define <4 x i16> @paaddu_i16x4(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: paaddu_i16x4:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    paaddu.h a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <4 x i16> @llvm.riscv.paaddu.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %tmp
}

declare <2 x i32> @llvm.riscv.paaddu.v2i32(<2 x i32>, <2 x i32>)

define <2 x i32> @paaddu_i32x2(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: paaddu_i32x2:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    paaddu.w a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %tmp = call <2 x i32> @llvm.riscv.paaddu.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %tmp
}
