// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p -O2 -emit-llvm %s -o - \
// RUN:     | FileCheck %s  -check-prefix=RV64P

#include <riscv_packed.h>

// RV64P-LABEL: @test_paadd_i8x8(
// RV64P-NEXT:  entry:
// RV64P-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <8 x i8>
// RV64P-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64P-NEXT:    [[TMP2:%.*]] = tail call <8 x i8> @llvm.riscv.paadd.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64P-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64P-NEXT:    ret i64 [[TMP3]]
//
int8x8_t test_paadd_i8x8(int8x8_t rs1, int8x8_t rs2) {
  return __riscv_paadd_i8x8(rs1, rs2);
}

// RV64P-LABEL: @test_paadd_i16x4(
// RV64P-NEXT:  entry:
// RV64P-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64P-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64P-NEXT:    [[TMP2:%.*]] = tail call <4 x i16> @llvm.riscv.paadd.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64P-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64P-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_paadd_i16x4(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_paadd_i16x4(rs1, rs2);
}

// RV64P-LABEL: @test_paadd_i32x2(
// RV64P-NEXT:  entry:
// RV64P-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64P-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64P-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.riscv.paadd.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64P-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64P-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_paadd_i32x2(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_paadd_i32x2(rs1, rs2);
}

// RV64P-LABEL: @test_paaddu_u8x8(
// RV64P-NEXT:  entry:
// RV64P-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <8 x i8>
// RV64P-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64P-NEXT:    [[TMP2:%.*]] = tail call <8 x i8> @llvm.riscv.paaddu.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64P-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64P-NEXT:    ret i64 [[TMP3]]
//
uint8x8_t test_paaddu_u8x8(uint8x8_t rs1, uint8x8_t rs2) {
  return __riscv_paaddu_u8x8(rs1, rs2);
}

// RV64P-LABEL: @test_paaddu_u16x4(
// RV64P-NEXT:  entry:
// RV64P-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64P-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64P-NEXT:    [[TMP2:%.*]] = tail call <4 x i16> @llvm.riscv.paaddu.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64P-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64P-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_paaddu_u16x4(uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_paaddu_u16x4(rs1, rs2);
}

// RV64P-LABEL: @test_paaddu_u32x2(
// RV64P-NEXT:  entry:
// RV64P-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64P-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64P-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.riscv.paaddu.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64P-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64P-NEXT:    ret i64 [[TMP3]]
//
uint32x2_t test_paaddu_u32x2(uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_paaddu_u32x2(rs1, rs2);
}

// RV64P-LABEL: @test_pasub_i8x8(
// RV64P-NEXT:  entry:
// RV64P-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <8 x i8>
// RV64P-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64P-NEXT:    [[TMP2:%.*]] = tail call <8 x i8> @llvm.riscv.pasub.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64P-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64P-NEXT:    ret i64 [[TMP3]]
//
int8x8_t test_pasub_i8x8(int8x8_t rs1, int8x8_t rs2) {
  return __riscv_pasub_i8x8(rs1, rs2);
}

// RV64P-LABEL: @test_pasub_i16x4(
// RV64P-NEXT:  entry:
// RV64P-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64P-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64P-NEXT:    [[TMP2:%.*]] = tail call <4 x i16> @llvm.riscv.pasub.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64P-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64P-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_pasub_i16x4(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pasub_i16x4(rs1, rs2);
}


// RV64P-LABEL: @test_pasub_i32x2(
// RV64P-NEXT:  entry:
// RV64P-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64P-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64P-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.riscv.pasub.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64P-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64P-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_pasub_i32x2(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_pasub_i32x2(rs1, rs2);
}


// RV64P-LABEL: @test_pasubu_u8x8(
// RV64P-NEXT:  entry:
// RV64P-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <8 x i8>
// RV64P-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64P-NEXT:    [[TMP2:%.*]] = tail call <8 x i8> @llvm.riscv.pasubu.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64P-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64P-NEXT:    ret i64 [[TMP3]]
//
uint8x8_t test_pasubu_u8x8(uint8x8_t rs1, uint8x8_t rs2) {
  return __riscv_pasubu_u8x8(rs1, rs2);
}


// RV64P-LABEL: @test_pasubu_u16x4(
// RV64P-NEXT:  entry:
// RV64P-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64P-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64P-NEXT:    [[TMP2:%.*]] = tail call <4 x i16> @llvm.riscv.pasubu.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64P-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64P-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_pasubu_u16x4(uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pasubu_u16x4(rs1, rs2);
}


// RV64P-LABEL: @test_pasubu_u32x2(
// RV64P-NEXT:  entry:
// RV64P-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64P-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64P-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.riscv.pasubu.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64P-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64P-NEXT:    ret i64 [[TMP3]]
//
uint32x2_t test_pasubu_u32x2(uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_pasubu_u32x2(rs1, rs2);
}
